// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace test2.Migrations
{
    [DbContext(typeof(_DbContext))]
    partial class _DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("test2.Models.Simulation", b =>
                {
                    b.Property<Guid>("id_simulasi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("bm")
                        .HasColumnType("int");

                    b.Property<string>("kode_barang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("nilai_bm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("nilai_komoditas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("uraian_barang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("waktu_insert")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_simulasi");

                    b.ToTable("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
